# Generated by Django 4.1.5 on 2023-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menufoods', '0002_food_special_price_alter_food_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='title',
        ),
        migrations.AddField(
            model_name='food',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
