# Generated by Django 4.1.5 on 2023-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menufoods', '0004_food_image_alter_food_discription_alter_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to='foodsImage'),
        ),
    ]
