# Generated by Django 4.1.5 on 2023-02-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_orderitem_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_orderd',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
