# Generated by Django 4.1.5 on 2023-02-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menufoods', '0005_alter_food_image'),
        ('user', '0003_remove_order_date_orderd_remove_orderitem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menufoods.food'),
        ),
    ]
