# Generated by Django 4.1.5 on 2023-02-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_fav_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='food',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='order',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
